# WeatherEvent 高级配置文件
# 适配新功能：增强触发条件、效果组合与传递、动态参数调整、API直接调用

# 全局配置
# 是否在玩家加入时发送天气信息
send-weather-info-on-join: true

# 是否在切换世界时发送天气信息
send-weather-info-on-world-change: true

# 是否仅在主世界发送信息
main-world-only: true

# 主世界名称
main-world-name: "world"

# 是否发送时间信息
send-time-info: true

# 天气信息消息
messages:
  weather-info-thunder: "当前天气：&5雷暴"
  weather-info-rain: "当前天气：&9下雨"
  weather-info-clear: "当前天气：&e晴朗"
  time-info-sunrise: "当前时间：&6日出"
  time-info-day: "当前时间：&e白天"
  time-info-sunset: "当前时间：&6日落"
  time-info-night: "当前时间：&1夜晚"
  rain-slip: "&c哎呀！下雨天路滑，你摔倒了！"

# 天气效果配置
effects:
  # 晴天效果
  clear:
    enabled: true
    # 生物群系限制 - 只在这些生物群系中生效
    biomes:
      - plains
      - forest
      - savanna
      - desert
    # 高度限制 - 只在这个高度范围内生效
    min-height: 60
    max-height: 320
    # 药水效果
    potion-effects:
      - type: SPEED
        level: [0, 1]  # 范围随机 0-1 级
        duration: [100, 200]  # 范围随机 100-200 ticks
      - type: JUMP
        level: 0
        duration: 200
    # 随机效果
    random-effects:
      chance: 0.2  # 20% 几率触发
      effects:
        - type: REGENERATION
          level: 0
          duration: 100
        - type: DAMAGE_RESISTANCE
          level: 0
          duration: 150
    # 标题显示 - 使用API直接调用
    title:
      enabled: true
      text: "§e阳光明媚"
      subtitle: "§7享受温暖的阳光吧，%player_name%！"
      fadeIn: 10
      stay: 70
      fadeOut: 20
      chance: 0.4  # 40% 几率显示
    # 声音效果 - 使用API直接调用
    sound:
      enabled: true
      resource: "entity.experience_orb.pickup"
      volume: 1.0
      pitch: 1.0
      chance: 0.6  # 60% 几率播放
    # 命令
    commands:
      chance: 0.05  # 5% 几率执行
      list:
        - "title %player% subtitle {\"text\":\"阳光明媚\",\"color\":\"yellow\"}"
        - "particle minecraft:happy_villager ~ ~1 ~ 0.5 0.5 0.5 0.1 10 force"
      # 连锁效果 - 命令执行后有几率触发其他效果
      chain-effects:
        bonus_effect:
          chance: 0.2  # 20% 几率触发
          effect-id: "healing_effect"

  # 雨天效果
  rain:
    enabled: true
    # 生物群系限制
    biomes:
      - forest
      - taiga
      - swamp
      - jungle
    # 光照限制 - 只在这个光照范围内生效
    min-light: 0
    max-light: 10
    # 药水效果
    potion-effects:
      - type: SLOW
        level: 0
        duration: 120
    # 随机效果 - 带前置条件
    random-effects:
      chance: 0.25
      # 前置条件 - 只有当玩家已经有缓慢效果时才可能触发
      prerequisites:
        type: has_potion_effect
        effect_type: SLOW
        level: 0
      effects:
        - type: WEAKNESS
          level: 0
          duration: 200
    # 动作栏消息 - 使用API直接调用
    action-bar:
      enabled: true
      text: "§b雨水淋湿了你的衣服"
      chance: 0.5
    # 声音效果 - 使用API直接调用
    sound:
      enabled: true
      resource: "weather.rain"
      volume: 0.8
      pitch: 1.0
      chance: 0.7
    # 命令
    commands:
      chance: 0.08  # 8% 几率执行
      list:
        - "title %player% actionbar {\"text\":\"雨水淋湿了你的装备\",\"color\":\"blue\"}"
        - "playsound minecraft:weather.rain ambient %player% ~ ~ ~ 0.5 1.0"
      # 连锁效果 - 命令执行后有几率触发其他效果
      chain-effects:
        slip_effect:
          chance: 0.25  # 25% 几率触发
          effect-id: "rain_slip"
    
    # 雨天打滑效果
    slip:
      enabled: true
      chance: 0.05  # 5% 几率触发打滑
      effect-id: "rain_slip"  # 引用共享效果

  # 雷暴效果
  thunder:
    enabled: true
    # 药水效果
    potion-effects:
      - type: WEAKNESS
        level: [0, 1]
        duration: [100, 150]
    # 命令 - 带连锁效果
    commands:
      chance: 0.1  # 10% 几率执行
      list:
        - "effect give %player% minecraft:glowing 5 0 true"
      # 连锁效果 - 命令执行后有几率触发其他效果
      chain-effects:
        lightning_strike:
          chance: 0.3  # 30% 几率触发
          effect-id: "small_lightning_strike"
    # 伤害配置
    damage:
      enabled: true
      chance: 0.15  # 15% 几率造成伤害
      amount: [2.0, 5.0]  # 范围随机 2-5 点伤害
    # 消息 - 使用API直接调用
    message:
      enabled: true
      text: "§8一道闪电划过天空！"
      chance: 0.4
    # 声音效果 - 使用API直接调用
    sound:
      enabled: true
      resource: "entity.lightning_bolt.thunder"
      volume: 1.0
      pitch: 1.0
      chance: 0.8

  # 夜晚效果 - 自定义天气效果
  night:
    enabled: true
    # 光照限制 - 只在黑暗环境中生效
    min-light: 0
    max-light: 4
    # 药水效果
    potion-effects:
      - type: NIGHT_VISION
        level: 0
        duration: 300
    # 动作栏消息
    action-bar:
      enabled: true
      text: "§8夜幕降临，小心周围的怪物"
      chance: 0.6
    # 命令
    commands:
      chance: 0.1  # 10% 几率执行
      list:
        - "playsound minecraft:ambient.cave ambient %player% ~ ~ ~ 0.3 0.8"
        - "particle minecraft:smoke ~ ~1 ~ 1 0.5 1 0.01 10 force"
      # 连锁效果 - 命令执行后有几率触发其他效果
      chain-effects:
        night_creature:
          chance: 0.15  # 15% 几率触发
          effect-id: "small_lightning_strike"

  # 洞穴效果 - 自定义天气效果
  cave:
    enabled: true  # 已启用，CaveEffect已实现
    # 高度限制 - 只在地下生效
    min-height: -64
    max-height: 40
    # 光照限制 - 只在黑暗环境中生效
    min-light: 0
    max-light: 7
    # 药水效果
    potion-effects:
      - type: NIGHT_VISION
        level: 0
        duration: 400
      - type: FAST_DIGGING
        level: 0
        duration: 200
    # 随机效果
    random-effects:
      chance: 0.15
      effects:
        - type: DAMAGE_RESISTANCE
          level: 0
          duration: 100
    # 声音效果
    sound:
      enabled: true
      resource: "ambient.cave"
      volume: 0.5
      pitch: 1.0
      chance: 0.4
    # 命令
    commands:
      chance: 0.07  # 7% 几率执行
      list:
        - "title %player% title {\"text\":\"深入洞穴\",\"color\":\"dark_gray\"}"
        - "effect give %player% minecraft:haste 10 0 true"
      # 连锁效果 - 命令执行后有几率触发其他效果
      chain-effects:
        cave_discovery:
          chance: 0.1  # 10% 几率触发
          effect-id: "healing_effect"

# 共享效果定义 - 可以被其他效果引用
shared-effects:
  # 小型闪电效果
  small_lightning_strike:
    # 声音
    sound:
      enabled: true
      resource: "entity.lightning_bolt.impact"
      volume: 1.0
      pitch: 0.8
    # 伤害
    damage:
      enabled: true
      chance: 0.6
      amount: [1.0, 3.0]  # 范围随机 1-3 点伤害
    # 消息
    message:
      enabled: true
      text: "§c你被闪电击中了！"
      chance: 1.0
  
  # 治愈效果
  healing_effect:
    # 药水效果
    potion-effects:
      - type: REGENERATION
        level: 1
        duration: 100
      - type: SATURATION
        level: 0
        duration: 60
    # 标题
    title:
      enabled: true
      text: "§a治愈"
      subtitle: "§7你感到一阵温暖"
      fadeIn: 10
      stay: 40
      fadeOut: 10
      chance: 1.0
  
  # 下雨打滑效果
  rain_slip:
    # 声音
    sound:
      enabled: true
      resource: "entity.player.hurt"
      volume: 1.0
      pitch: 1.0
      chance: 1.0
    # 伤害
    damage:
      enabled: true
      chance: 0.3
      amount: 1.0
    # 消息
    message:
      enabled: true
      text: "&c哎呀！下雨天路滑，你摔倒了！"
      chance: 1.0