# WeatherEvent 默认配置文件

# 全局配置
# 是否在玩家加入时发送天气信息
send-weather-info-on-join: true

# 是否在切换世界时发送天气信息
send-weather-info-on-world-change: true

# 是否仅在主世界发送信息
main-world-only: true

# 主世界名称
main-world-name: "world"

# 是否发送时间信息
send-time-info: true

# 共享效果配置
shared-effects:
  # 雨天打滑效果
  rain_slip:
    # 前置条件 - 只有在雨天且在户外时才可能触发
    conditions:
      type: "weather"
      weather: "rain"
    commands:
      list:
        - "title %player% actionbar {\"text\":\"你滑倒了！\",\"color\":\"red\"}"
        - "playsound minecraft:entity.player.hurt ambient %player% ~ ~ ~ 1.0 1.0"
    damage:
      enabled: true
      chance: 0.8
      amount: 1.0
      
  # 小型闪电打击效果
  small_lightning_strike:
    commands:
      list:
        - "execute at %player% run particle minecraft:electric_spark ~ ~1 ~ 0.5 0.5 0.5 0.1 10 force"
        - "playsound minecraft:entity.lightning_bolt.thunder ambient %player% ~ ~ ~ 0.5 1.0"
    damage:
      enabled: true
      chance: 0.3
      amount: [1.0, 3.0]
      
  # 治疗效果
  healing_effect:
    commands:
      list:
        - "particle minecraft:heart ~ ~1 ~ 0.5 0.5 0.5 0.1 5 force"
    chain-effects:
      # 连锁效果 - 治疗效果可能触发更强的治疗效果
      strong_healing:
        chance: 0.2
        effect-id: "strong_healing_effect"
        delay: 40  # 延迟2秒触发
        conditions:
          type: "has_potion_effect"
          effect_type: "REGENERATION"

  # 强力治疗效果
  strong_healing_effect:
    commands:
      list:
        - "particle minecraft:heart ~ ~1 ~ 0.5 0.5 0.5 0.1 10 force"
        - "title %player% actionbar {\"text\":\"强力治疗！\",\"color\":\"green\"}"
        
  # 沙尘暴效果
  sandstorm_effect:
    potion-effects:
      - type: SLOW
        level: 1
        duration: 200
      - type: BLINDNESS
        level: 0
        duration: 100
    commands:
      list:
        - "particle minecraft:dust 0.8 0.7 0.4 1 ~ ~1 ~ 1 1 1 0.1 20 force"
        - "playsound minecraft:weather.rain ambient %player% ~ ~ ~ 0.8 0.7"
    message:
      enabled: true
      text: "§6沙尘暴来袭，视线受阻！"
      chance: 0.6
      
  # 暴风雪效果
  blizzard_effect:
    potion-effects:
      - type: SLOW
        level: 2
        duration: 200
      - type: WEAKNESS
        level: 1
        duration: 200
    commands:
      list:
        - "particle minecraft:snowflake ~ ~1 ~ 1 1 1 0.1 30 force"
        - "particle minecraft:cloud 0.8 0.8 1.0 1 ~ ~1 ~ 1 1 1 0.1 20 force"
        - "playsound minecraft:weather.rain ambient %player% ~ ~ ~ 0.8 2.0"
    message:
      enabled: true
      text: "§b暴风雪！寒冷刺骨！"
      chance: 0.6

# 生物群系天气效果配置
biome-weather:
  enabled: true
  update-interval: 20  # 效果更新间隔，单位为tick
  # 为不同生物群系定义独特的天气效果
  biomes:
    # 沙漠生物群系
    desert:
      # 沙漠中的特殊天气 - 沙尘暴
      weather:
        # 晴天时可能触发沙尘暴
        clear:
          enabled: true
          chance: 0.1  # 10% 几率在晴天触发沙尘暴
          effects:
            - type: sandstorm
              duration: [200, 400]  # 持续时间10-20秒
        # 雨天时的特殊效果（沙漠中很少下雨）
        rain:
          enabled: true
          chance: 0.01  # 1% 几率下雨
          potion-effects:
            - type: REGENERATION
              level: 1
              duration: 200
          message:
            enabled: true
            text: "§a奇迹！沙漠中下雨了！"
            chance: 1.0
            
    # 雪原生物群系
    snowy_plains:
      # 雪原中的特殊天气 - 暴风雪
      weather:
        # 下雪时可能触发暴风雪
        rain:
          enabled: true
          chance: 0.15  # 15% 几率触发暴风雪
          effects:
            - type: blizzard
              duration: [300, 600]  # 持续时间15-30秒
        # 晴天时的特殊效果
        clear:
          enabled: true
          potion-effects:
            - type: SPEED
              level: 0
              duration: 200
          message:
            enabled: true
            text: "§b雪后初晴，空气清新"
            chance: 0.3
            
    # 丛林生物群系
    jungle:
      # 丛林中的特殊天气 - 湿热
      weather:
        # 任何天气下都可能触发湿热效果
        any:
          enabled: true
          chance: 0.2  # 20% 几率触发湿热效果
          potion-effects:
            - type: HUNGER
              level: 0
              duration: 200
            - type: SLOW
              level: 0
              duration: 100
          message:
            enabled: true
            text: "§2丛林湿热难耐"
            chance: 0.5
            
    # 沼泽生物群系
    swamp:
      # 沼泽中的特殊天气 - 毒雾
      weather:
        # 夜晚时可能触发毒雾
        night:
          enabled: true
          chance: 0.1  # 10% 几率触发毒雾
          potion-effects:
            - type: POISON
              level: 0
              duration: 100
            - type: SLOW
              level: 0
              duration: 200
          message:
            enabled: true
            text: "§2沼泽中升起毒雾"
            chance: 0.7
            
    # 下界荒地生物群系
    nether_wastes:
      # 下界中的特殊天气 - 火雨
      weather:
        # 任何时候都可能触发火雨
        any:
          enabled: true
          chance: 0.05  # 5% 几率触发火雨
          damage:
            enabled: true
            chance: 0.3
            amount: [1.0, 3.0]
          commands:
            list:
              - "particle minecraft:lava ~ ~10 ~ 0.5 0.5 0.5 0.1 5 force"
              - "particle minecraft:flame ~ ~10 ~ 1 1 1 0.1 10 force"
          message:
            enabled: true
            text: "§c下界火雨！小心躲避！"
            chance: 0.8

# 天气效果配置
effects:
  # 晴天效果
  clear:
    enabled: true
    # 生物群系限制 - 只在这些生物群系中生效
    biomes:
      - plains
      - forest
      - savanna
      - desert
    # 高度限制 - 只在这个高度范围内生效
    min-height: 60
    max-height: 320
    # 药水效果
    potion-effects:
      - type: SPEED
        level: [0, 1]  # 范围随机 0-1 级
        duration: [100, 200]  # 范围随机 100-200 ticks
      - type: JUMP
        level: 0
        duration: 200
    # 随机效果
    random-effects:
      chance: 0.2  # 20% 几率触发
      effects:
        - type: REGENERATION
          level: 0
          duration: 100
        - type: DAMAGE_RESISTANCE
          level: 0
          duration: 150
    # 标题显示
    title:
      enabled: true
      text: "§e晴天"
      subtitle: "§7天气晴朗"
      fadeIn: 10
      stay: 70
      fadeOut: 20
      chance: 0.5
    # 声音效果
    sound:
      enabled: true
      resource: "entity.experience_orb.pickup"
      volume: 1.0
      pitch: 1.0
      chance: 0.5
    # 命令
    commands:
      chance: 0.05  # 5% 几率执行
      list:
        - "title %player% subtitle {\"text\":\"阳光明媚\",\"color\":\"yellow\"}"
        - "particle minecraft:happy_villager ~ ~1 ~ 0.5 0.5 0.5 0.1 10 force"
      # 连锁效果 - 命令执行后有几率触发其他效果
      chain-effects:
        bonus_effect:
          chance: 0.2  # 20% 几率触发
          effect-id: "healing_effect"
          delay: 20  # 延迟1秒触发
          conditions:
            type: "has_potion_effect"
            effect_type: "SPEED"

  # 雨天效果
  rain:
    enabled: true
    # 生物群系限制
    biomes:
      - forest
      - taiga
      - swamp
      - jungle
    # 光照限制 - 只在这个光照范围内生效
    min-light: 0
    max-light: 10
    # 药水效果
    potion-effects:
      - type: SLOW
        level: 0
        duration: 100
    # 随机效果 - 带前置条件
    random-effects:
      chance: 0.25
      # 前置条件 - 只有当玩家已经有缓慢效果时才可能触发
      prerequisites:
        type: has_potion_effect
        effect_type: SLOW
        level: 0
      effects:
        - type: WEAKNESS
          level: 0
          duration: 200
    # 动作栏消息
    action-bar:
      enabled: true
      text: "§b下雨了"
      chance: 0.5
    # 声音效果
    sound:
      enabled: true
      resource: "weather.rain"
      volume: 0.8
      pitch: 1.0
      chance: 0.5
    # 命令
    commands:
      chance: 0.08  # 8% 几率执行
      list:
        - "title %player% actionbar {\"text\":\"雨水淋湿了你的装备\",\"color\":\"blue\"}"
        - "playsound minecraft:weather.rain ambient %player% ~ ~ ~ 0.5 1.0"
      # 连锁效果 - 命令执行后有几率触发其他效果
      chain-effects:
        slip_effect:
          chance: 0.25  # 25% 几率触发
          effect-id: "rain_slip"
          delay: 10  # 延迟0.5秒触发
          conditions:
            type: "light_level"
            min: 0
            max: 7
    # 雨天打滑效果
    slip:
      enabled: true
      chance: 0.05  # 5% 几率触发打滑
      effect-id: "rain_slip"  # 引用共享效果

  # 雷暴效果
  thunder:
    enabled: true
    # 药水效果
    potion-effects:
      - type: WEAKNESS
        level: [0, 1]
        duration: [100, 150]
    # 消息
    message:
      enabled: true
      text: "§8打雷了！"
      chance: 0.5
    # 声音效果
    sound:
      enabled: true
      resource: "entity.lightning_bolt.thunder"
      volume: 1.0
      pitch: 1.0
      chance: 0.7
    # 命令 - 带连锁效果
    commands:
      chance: 0.1  # 10% 几率执行
      list:
        - "effect give %player% minecraft:glowing 5 0 true"
      # 连锁效果 - 命令执行后有几率触发其他效果
      chain-effects:
        lightning_strike:
          chance: 0.3  # 30% 几率触发
          effect-id: "small_lightning_strike"
          delay: 5  # 延迟0.25秒触发
          conditions:
            type: "random"
            chance: 0.5
    # 伤害配置
    damage:
      enabled: true
      chance: 0.15  # 15% 几率造成伤害
      amount: [2.0, 5.0]  # 范围随机 2-5 点伤害

  # 夜晚效果 - 自定义天气效果
  night:
    enabled: true
    # 光照限制 - 只在黑暗环境中生效
    min-light: 0
    max-light: 4
    # 药水效果
    potion-effects:
      - type: NIGHT_VISION
        level: 0
        duration: 300
    # 动作栏消息
    action-bar:
      enabled: true
      text: "§1夜晚降临"
      chance: 0.3
    # 命令
    commands:
      chance: 0.1
      list:
        - "particle minecraft:soul_fire_flame ~ ~1 ~ 0.5 0.5 0.5 0.1 5 force"
      # 连锁效果
      chain-effects:
        # 夜晚效果可能触发隐身效果
        invisibility:
          chance: 0.1
          effect-id: "night_invisibility"
          delay: 60  # 延迟3秒触发

# 消息配置
messages:
  weather-info-thunder: "当前天气：&5雷暴"
  weather-info-rain: "当前天气：&9下雨"
  weather-info-clear: "当前天气：&e晴朗"
  time-info-sunrise: "当前时间：&6日出"
  time-info-day: "当前时间：&e白天"
  time-info-sunset: "当前时间：&6日落"
  time-info-night: "当前时间：&1夜晚"
  rain-slip: "&c哎呀！下雨天路滑，你摔倒了！"
  rain-start: "&9开始下雨了！"
  rain-stop: "&e雨停了，天气转晴！"
  thunder-start: "&5雷暴开始了，小心闪电！"
  thunder-stop: "&e雷暴结束了！"